### ISSUE TITLE
Uninitialized Refinery::Products::Categories::Finder

### ISSUE THREAD

**Issue by vlebedeff** [bisscomm/refinerycms-products#14]
When I edit the code without restarting a development web server, I get
```
NameError: uninitialized constant Refinery::Products::Categories::Finder
```
It goes away after a restart, but it's a pain.

**Comment by bricesanchez** [comment]
Yes, it's the same issue than #11, i don't know yet why it occurs.

**Comment by vlebedeff** [comment]
@bricesanchez It looks like I've worked around it with
```ruby
require_dependency 'refinery/products/categories/url'
require_dependency 'refinery/products/categories/finder'
```
added to `config/initializers/refinery/products.rb`.

Don't know whether it's a good practice, but it saves me from restarts.
